apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: customer-events-producer
  namespace: customer-events
spec:
  interval: 5m

  chart:
    spec:
      chart: ./apps/customer-events-producer/helm/customer-events-producer
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m

  values:
    image:
      repository: ghcr.io/ohunilu/customer-events-producer
      tag: "dev"
      pullPolicy: IfNotPresent

    imagePullSecrets:
      - name: ghcr-pull-secret

    kafka:
      topic: orders
      secretName: orders-producer-credentials