apiVersion: v1
data:
    alertmanager.yaml: ENC[AES256_GCM,data:cx6Byd7MVZW60OGKrE+rKTJGrRi4oyxVMXtIkctlNdjqJZo0gCVQyC4svy4DCiagKoC0C4lAFwtokx3TtzOW4WE+e1hrCRdQm426susV3eWZQAQx/B7QoEOalxAmbTCcE1dtInKWypZERj1/e/NjViURf8qdYMki0vPd49ZO/MwKfHu4XkvNdhpNy9oIbZoztx6j+iuBMOfrOVFrbfN6q2+gPRMI9mwB52NQ3InzfEDWgNOb5jkBpfJyOpWYjxTSTTRtlEaWi3wtBcFG3LE14pln/pDi+yIBDhCNLvV69w09ftUtU7Km4wAardAHZ/nD+HMbFZLEzZb8xLgrwfi+DbxgFHgrpFgfGGY0mE2Sn/CzXPOVbfmjrORhgZJj9hO2vO3bQKrwAcp378S6tP6mLAO/4RmKnHm68sxkaa4m8Gf6unSZAE4Nw9MH4sMEq9E1GydcnaGC5vx0eEKREje35P8zkhAoppQhNY29Q/xlbBD4jsCFAx6FaR2WoeQC/6QaK2vjFc/OZt4ZOikVbfLhFt0ZbXcqgoYB6annQrAcSIpo/NEKYOlzTCZC78nZbeeUq79cS7kVF5wW6d5SCcMPAG2n5qLmKHy1aFbApWnXjf/y2ezX4fRa2Y0CEzyBb+/G8xh4WgE32gdORGP9fPQeYmInWKQsGhU4qQK0iYES11d7aQejPdSU4eutncjzm+yUyFnLAV0ewH1TMZyZHo/6swaqZswEiBgjLBwdJynUIcO4QFE8JnL829UpdXzP7pd58SU7RaTG90Itn8hC150mC9VAihShUnEWGNeqlchZ/Prygi77nBKD+937YvbergzYvHn7/sbEAHgExzBl+PPK+4LF4hx5Kq/Sg+TjybfpMCEtKTjACayf3+3DKjk8RFg/Oq5bAG99U74aZjaKtJ+9MXFFw0QrEttII5q0i5L+FKmyNeWr6twVF4GOwXPoJagelMSIb5tmwS4I/ZCFjXim+h5FLZRGHZUifkEnOVFt3h9gfyubQjIBoNQFvWyEhfcsq8R7sbTdJ7JohAgqvlr45eG0vqsjVJ+qgdzs6qVVciSDkHCBb/LKC9b4+5V6Old5fRnK+4eI4od2YSEDo/jSYvKiimLpyBKVJNJrjc6Crb3PWuqu,iv:+CwkOckGqHLpuj6HBfy26+3YNq68jYOPH8DZqNquRsI=,tag:AexLZHzLTHFgnuonDStHmQ==,type:str]
kind: Secret
metadata:
    name: alertmanager-kube-prometheus-stack-alertmanager
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSkt0U0RiZUc3aDR4cENs
            a0ZJMlZSYmhVdU1iWWw3OWplMGlIdHFlUTE4ClhldUtHTUJDRTBMa2Q3cmhLNERw
            SzRoQzlHNUJXMEpNZVk3UzlyVzJxYlkKLS0tIHVXRzdtcEJoaHVVYk9ud0MwWU1u
            N3BUQUttbWlwOGFhd2xTclZsRDJMWFkKL2yncBuib+3pXEXEGk86n3dGhcQFSxwg
            B2shBh9xIpLnKLxveSOsStfFdei4rmYYYfaOkEkPOoQxRfU9yN2k3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xyjvdqf803kve09gjwre76282sqhaggcv8ghjqpauecfaapkn4ms5svp8l
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T18:26:18Z"
    mac: ENC[AES256_GCM,data:eN7IYAeGZSrrZqXsp4bc+w2AU+vnIBeJJsvej8WMUhC3+McxH/Fl/3FeejqHl63wCv7oDU+L6fEJIPfe+hxmyBljteY4HkCOAwZ4GsLPF+QmNDGB6F/PUA8vTZd98kpJbU3aEYgt2kM5+dCSo8kNAL+bq8HYIiyVQMTj6c0ivAg=,iv:7hjML4tbmcEdFva2ATCSekkGlbgkEYApwMn/MN0Yvc8=,tag:ueJkT0ZaPXZIZ6pENpQF/g==,type:str]
    version: 3.13.3
