apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:kw73FTt2SbQTkG+Rjj079c9WYi2UQFl5NekYDVoJgYQSI+Qk5D0jn4tAMR3gyaWAUA1o7zRgqRHe/NC15GBsQkd0kAzONy+4TrhI1ns5tt/55iIX26E7NdxBIuDYvy6b2w6psa/AJYucQidhXTpX0RYaiZ28OehDYfKs5LZG2MT6GVZf61MS1wMCZU75YXMkZNewIoQsczbjbk5ZjWtjgJ8IGKQAyd+mxc3BOd65kPUIzsmCtkd6TADlxXClwyoXBqmHYjnipwnvfvL+sJlHZSqfuUF3iiAyAV7eFnx03hY9LJAAuqDPkA==,iv:fOUTuMudw0QhCVY3Sua38GTgKow1uAS1IllPbmS18uw=,tag:aLDNgdhqOV2A4xrJsYPdWA==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: customer-events
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aXhueVhYd0RES2JIOUNW
            NTBjNTVUUzVXZUNLMC9ua0MxY1oyR3JkQmdJCkplNjAwUnZrd1k0TG10L0t6V1VK
            S1VTcTV2TzBIZFN1Yk1vYi9oYytHM3cKLS0tIHBpSzV3bDM0VWJpUFIxWURGOWdo
            QUU0L0dkSURHUEIwWERxaGkxeEloUTgK+bNgFNtEi6JqvdcAT+NANmuIfmdlfsxz
            D3b1Zf1JTqh4D4GF8VVLheZWXSfVEJ5thsDv0gpBSbqB2/kfhf7E8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xyjvdqf803kve09gjwre76282sqhaggcv8ghjqpauecfaapkn4ms5svp8l
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T21:15:20Z"
    mac: ENC[AES256_GCM,data:RT4fNb0U1cTynKveyYbY4hBcJiUEhLBr3cfmCMimEPXMSvRmr5jtP5mW8WcrbZkhwsGEq3uEKiRD4lEp5hB3yuW0ZQ8bAzqcp2lWicu7urJobwToFkcFX1OD0jUBSHnnQQa4jBoqb/cgexLyFqLBuwti/kfgxUoB4fw/CkicBQs=,iv:jtdVCdoseZ2AxyGGiujR2Olu518fDwkosRvnNXUtDeI=,tag:5BfE6/GRGR/+hGiXGjOSEA==,type:str]
    version: 3.13.3
