apiVersion: v1
kind: Secret
metadata:
    name: orders-producer-credentials
    namespace: customer-events
type: Opaque
stringData:
    bootstrap.servers: ENC[AES256_GCM,data:pR8X5Em9kysASb2myNwhcaqnUKBuMRjpGk8atJIbugDxPOOxUmkC/ywFU5X+tQE7BNBwZHg9,iv:d9TnMd9jwGoprhXdkp+XSW33DRXq0dqyll0y6K0kdrE=,tag:z4yqizi2Y03vMMgPDMsj2g==,type:str]
    api.key: ENC[AES256_GCM,data:gkuMB/psqauZKpwCX1M9Fw==,iv:bEliYPDbRjh5gbWDk9cW4NaP0PRRjpJVJLtrXhyY+gk=,tag:WhPhMppkGf8WNcqHDxUMIQ==,type:str]
    api.secret: ENC[AES256_GCM,data:onUFcPQwnOYjXatCKa7A1c13TodOCcL7+7E0Owu63Y3IPzbDiCE7CmUXGTsgezy9/Smi4eigDTsYyixzDGnXOg==,iv:QNF2NYKjrgjnikRVvEVksEab2rIKqpqzSdIXuT5QNe4=,tag:OSPkCtjBgfLG/v3Jdvkzbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcU4zWE1ocHFiK3ZIOE9M
            Z3cwd0gzUGVMNzV4ajhoVjlUWExCOGZSVENvCkpVR0JvejB1VnNKeE55cThIMTZz
            QmFRZVl1Q3NjbFh5OG5jZGg2RGRyWDAKLS0tIGE2ZnVYcmNtcDVjR0N3Z0V0aHBH
            YUZzMENqekhhS21lVTFSbitPbzB0aWsKjeHaeN97mrS6ucUp3c2pNHcKh73vi5mO
            wraFP/GVkfhUQCHi7n1TfmiZKQrKW5/ZvhStntmH5JxZKhq3FMFxZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xyjvdqf803kve09gjwre76282sqhaggcv8ghjqpauecfaapkn4ms5svp8l
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T15:40:45Z"
    mac: ENC[AES256_GCM,data:ZQ5GvoMk+TDRQ8RtLuM6XetcywmvU/W33yA4XLn7a1gX882h/+aSHH3a2x/MHQF7jpLFfTstLe0pdmPtmyFZVz3IWotFnjUDYBaPVRAspTrjS16vIxEW1BpGDYswewZH+BoHY0A13mJqTPTRFssZnYeQ8JOf4Pz6NYQ4U35e32c=,iv:VRB7tsxr2UA9Yo8ruLEvOaQg50Uxe6Salm6XxNsvvVk=,tag:UU+eSNuU/Ycflu+a+O0ZRA==,type:str]
    version: 3.13.3
